### ISSUE TITLE
Add "just activate and you are done" in the description 

### ISSUE THREAD

**Issue by 00travelgirl00** [pluginkollektiv/checksum-verifier#13]
As far as I have seen, this plugin does not have a setting user interface. 

So I would suggest du add a little notification about that in the plugin description like it is in Crazy Lazy. This would increase the user experience, so their are not starting looking for the settings page. 

<img width="934" alt="bildschirmfoto 2017-11-20 um 23 16 54" src="https://user-images.githubusercontent.com/21318377/33046547-584dd0b0-ce49-11e7-9a68-224f1b12ad7e.png">

**Comment by bueltge** [comment]
Really welcome. Would you add an pull request or the description, that we should add on the plugin file and maybe also the readme?

**Comment by 00travelgirl00** [comment]
I just made a Pull Request for that: #14

**Comment by bueltge** [comment]
fixed with #14

**Comment by bueltge** [comment]
Hi @stklcode 
Can you release this small changes on wp.org, without change of the tag? Thx. I can't do this, not enough rights on this svn repository.
It is no functional changes, so that we should not change the release, version in my opinion. To much for an update on all installed instances.

**Comment by stklcode** [comment]
Hi @bueltge . Would be an honor to do so, but unfortunately my rights are also insufficient :disappointed:

**Comment by bueltge** [comment]
hm. :(
OK, I will ask vor rights in the slack channel, so that we can work faster without problems.

**Comment by bueltge** [comment]
Now, we are live ;) Thanks a all :tada:
