### ISSUE TITLE
Check for Gutenberg compatibility

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/checksum-verifier#15]
WordPress 5.0 will be here soon. Time for us to check, if our plugins are compatible with the Gutenberg Editor and WP 5.0 (a beta version is yet to be published). 

- [x] check (Gutenberg) editor with this plugin
- [x] check plugin settings site with active Gutenberg
- [x] fix potential issues
- [ ] add `Tested up to: 5.0` to the plugins readme
- [ ] publish changes as minor update or with upcoming plugin update

**Comment by stklcode** [comment]
Just tested on the latest 5.0 and 5.1 releases with Gutenberg 4.1.1.
Install -> activate -> deactivate -> activate -> trigger cron -> deactivate -> uninstall.
No issues detected.

Not really surprising, as this plugin is completely headless, but a quick test didn't really hurt :smiley:
