### ISSUE TITLE
wp plugin status

### ISSUE THREAD

**Issue by edwardsmarkf** [pluginkollektiv/checksum-verifier#16]
hello - TOTALLY AWESOME PLUGIN!    there appears to be no way to manually run this extraordinarily useful plugin without removing it and reinstalling it.   any better suggestions?   

note: this found several malware issues that quttera missed.

**Comment by stklcode** [comment]
> there appears to be no way to manually run this extraordinarily useful plugin without removing it and reinstalling it.

Deactivate and activate is in fact enough, no need to completely uninstall it.

> any better suggestions?

Let's try the other way around: What would you like to see?

I could imagine multiple enhancements here like
* a complete "settings" page with "Scan now" button and probably some more flags (e.g. interval configuration #9)
* a "Scan now" link in the plugin metadata on the plugin page
* a button in the admin bar or on the dashboard

**Comment by edwardsmarkf** [comment]
>>>  Let's try the other way around: What would you like to see?

I am but a mere WP mortal in awe of plugin developers.   Yes, indeed a
'scan-now' option would be wonderful.

Thank you,

Mark Edwards

**Comment by stklcode** [comment]
> are you sorry you asked now??  

No, thanks very much for your answer!
Definitely useful input for a decision about the future of this plugin. There are already some minor points which require a "keep it headless" or "add a settings/admin page" decision.

> is there any way to include the results from the last run, something other than email? [...]

I first thought "hell no, don't spam me", but you're absolutely right as this is a matter of trust - you don't know if the plugin failed to send an email or there is really no issue.

> and maybe a schedule option?  i would like to run checksum-verifier several times a day.

Strongly related to #9, if the time is adjustable why not the interval...

Think we should discuss options here whether to add and document filters for these features or introduce a settings page, which could also show the last e.g. 10 results to get an overview of the activity.

**Comment by edwardsmarkf** [comment]
hi stefan - another thought (for us privileged linux people) -- is there a
cli command to start the search manually??  thinking using my good friend
"crontab" fo the task, and run every 15 minutes or so.

note:  there is a really nasty one going around that does bitcoin mining!
this is the worst malware i have come across since all it does is quietly
steal cpu cycles.  this one took several days to track down, and
unfortunately, now it seems to have returned.  even quttera missed it,
although after reporting it, quttera quickly included it in their
virus-check.

Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
Torsten gave me an excellent suggestion to run this plugin hourly using the wp-control plugin:

> Torsten Landsiedel wrote:
>
> At the moment we are using a WP Cron daily:
> https://github.com/pluginkollektiv/checksum-verifier/blob/8a909f67091f71734747382d2756d6b5a65d173a/inc/class-checksum-verifier.php#L270-L276
> 
> As this is set up on activation I think you could change the interval to something else with tools like this:
> https://de.wordpress.org/plugins/wp-crontrol/

**Comment by stklcode** [comment]
The complete functionality has been recently merged into [Antivirus](https://w.org/plugins/antivirus/) (pluginkollektiv/antivirus#56), which features the same daily cron job plus a UI and two additional scans.

Next Antivirus verison has not been released yet. However new features will most likely not be added to this plugin anymore. So much for "plugin status".
