### ISSUE TITLE
Use dash for the plugin text domain

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/checksum-verifier#2]
From the [WordPress Codex](https://codex.wordpress.org/I18n_for_WordPress_Developers#Text_Domains):

> If your plugin is a single file called my-plugin.php or it is contained in a folder called my-plugin the domain name should be my-plugin. The text domain name must use dashes and not underscores.

Simply put, the text domain should match the plugin folder (`checksum-verifier` instead of `checksum_verifier`)

**Comment by timse201** [comment]
can be closed

**Comment by bueltge** [comment]
A reference of the commit to the issue would much better, for later. Please.
