### ISSUE TITLE
Allow to set the time of day when check runs

### ISSUE THREAD

**Issue by chesio** [pluginkollektiv/checksum-verifier#9]
In other words allow the check to be scheduled for low traffic hours.

If we want to keep the plugin headless (without UI), this could be implemented via a filter. Also it should be mentioned somewhere in readme that an external cron job should be set in such case to trigger WP-Cron on time.

**Comment by stklcode** [comment]
Filter would be a possibility. At the moment it is the time of activation. 
I would not not change this, so it always performs a one-time check on activation, but triggers the Cron job according to a filter - if set - with fallback to current behavior.

**Comment by patrickrobrecht** [comment]
Closed in favor of https://github.com/pluginkollektiv/antivirus/issues/80
